<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

class User extends ActiveRecord
{
    public static function tableName()
    {
        return 'users';
    }

    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub

        $tweetIds = Tweet::find()
            ->select('id')
            ->where(['user_id' => $this->id])
            ->asArray()
            ->all();

        Hashtag::deleteAll(['tweet_id' => ArrayHelper::getColumn($tweetIds, 'id')]);
        Tweet::deleteAll(['user_id' => $this->id]);
    }
}
